### ISSUE TITLE
R-T5.1-7: Support of FaaS deployment to AWS cloud   platform

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#11]
ID: | R-T5.1-7
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy TOSCA blueprint to AWS
Requirement: | Support of FaaS deployment to AWS cloud   platform
Extended   Description: | The TOSCA bluprints and Ansible playbooks   should be developed to deploy RADON model on AWS cloud platform
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Test if such playbooks and blueprints are   available in Template Library repository and its possible to deploy toy   example to AWS cloud platform only using playbooks and blueprints from   Template Library.

**Comment by cankarm** [comment]
All required templates are already available in the Template library:
```
$ xopera-template-library template list | grep -B 1 -A 4  Aws
id: 2
shorthandName: AwsBucket
typeUri: radon.nodes
templateTypeId: 7
publicAccess: True
createdBy: 1
--
id: 3
shorthandName: AwsLambda
typeUri: radon.nodes.function
templateTypeId: 7
publicAccess: True
createdBy: 1
--
id: 4
shorthandName: AwsBucketNotification
typeUri: radon.nodes.triggers
templateTypeId: 7
publicAccess: True
createdBy: 1
--
id: 5
shorthandName: AwsRole
typeUri: radon.policies
templateTypeId: 7
publicAccess: True
createdBy: 1
--
id: 6
shorthandName: AwsApiGateway
typeUri: radon.nodes.triggers
templateTypeId: 7
publicAccess: True
createdBy: 1
--
id: 13
shorthandName: DemoBlueprintAws
typeUri: node.blueprint
templateTypeId: 10
publicAccess: True
createdBy: 1
```

**Comment by cankarm** [comment]
As initial templates to form basic AWS FaaS operations are present, I'm closing this issue.

**Comment by gcasale** [comment]
Closed state approved.
