### ISSUE TITLE
R-T5.2-8: Support of FaaS_deployment to Google cloud platform

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#12]
ID: | R-T5.2-8
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy TOSCA blueprint to Google
Requirement: | Support of FaaS_deployment to Google   cloud platform
Extended   Description: | The TOSCA blueprints and Ansible   playbooks should be developed to deploy RADON model on Google Cloud
Priority: | Could have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Test if such playbooks and blueprints are   available in Template Library repository and the possibility to deploy toy   example to Google Cloud platform only using playbooks and blueprints from   Template Library.

**Comment by anzoman** [comment]
This is currently in backlog and will probably be implemented in the next month or two.

**Comment by anzoman** [comment]
The blueprint with thumbnail generator GCP application is here: https://github.com/radon-h2020/demo-tosca-blueprint-gcp and it works perfectly. This means that the issue can now be closed.
