### ISSUE TITLE
R-T5.2-9: Support of FaaS deployment to Azure cloud platform

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#13]
ID: | R-T5.2-9
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy TOSCA blueprint to Azure
Requirement: | Support of FaaS deployment to Azure cloud   platform
Extended   Description: | The TOSCA bluprints and Ansible playbooks   should be developed to deploy RADON model on Azure
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Test if such playbooks and blueprints are   available in Template Library repository and its possible to deploy toy   example to Google Cloud platform only using playbooks and blueprints from   Template Library.

**Comment by anzoman** [comment]
@cankarm this is done as we have TOSCA blueprints that can deploy services to Microsoft Azure cloud:

- [thumbnail-generator](https://github.com/radon-h2020/demo-tosca-blueprint-azure-function)
- [AWS-Azure connection with image-resize and image-watermark functionalities](https://github.com/radon-h2020/demo-tosca-blueprint-faas-aws-azure)

**Comment by cankarm** [comment]
OK, @anzoman thanks for putting this out!
