### ISSUE TITLE
R-T5.2-10: Support deployment to regular VMs

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#14]
ID: | R-T5.2-10
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy my application to regular VMs
Requirement: | Support deployment to regular VMs
Extended   Description: | The TOSCA blueprints and Ansible   playbooks should be developed to deploy RADON model on regular VMs
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Test if such playbooks and blueprints are   available in Template Library repository and its possible to deploy toy   example to regular VMs.

**Comment by anzoman** [comment]
Currently [xOpera](https://github.com/xlab-si/xopera-opera) supports deployment to a remote VMs. User should have SSH keys configured (`~/.ssh/config` file can be helpful here) and then he can use `OPERA_SSH_USER` to state which user he wants to connect as. We have prepared some examples of TOSCA blueprints that can be deployed to a remote VM, especially OpenFaaS solution is interesting and is available here: https://github.com/radon-h2020/demo-tosca-blueprint-openfaas.

**Comment by anzoman** [comment]
This is fully supported (we also have the [support for private SSH files](https://github.com/radon-h2020/radon-delivery-toolchain/issues/44) used when connecting to the VM, blueprints that this was tested with are also available in the Template library and on GitHub) and I will close the issue.
