### ISSUE TITLE
R-T5.4-1: The data pipeline module of the Orchestrator must be able to orchestrate data pipelines

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#16]
ID: | R-T5.4-1
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy data pipelines and control their life-cycle using RADON   toolchain
Requirement: | The data pipeline module of the Orchestrator must be able to orchestrate data pipelines
Extended   Description: | Orchestrator  must provide support for orchestrating data   pipelines.
Priority: | Must have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Evaluate whether the tool is able to   successully deploy data pipelines which have been defined using RADON models.

**Comment by chinmaya-dehury** [comment]
@cankarm , Can you please add "Data Pipeline" label to this issue?

**Comment by chinmaya-dehury** [comment]
The required basic templates, implementation file and other related files are ready and can be orchestrated with the RADON Orchestrator. A demo can be seen [here](https://www.youtube.com/watch?v=_6zTEj2ZJ54). Please verify for approval @gcasale .

**Comment by gcasale** [comment]
This unlikely to be the final version, if so the requirement needs to remain open.

**Comment by chinmaya-dehury** [comment]
All the requirements are fulfilled. 
Some are waiting for approval (#18 , #19 , #21 , #22 ), some are approved to be closed (#50 , #17 , #20 ) and requirement #23 is closed.

This final issue can be closed if above-mentioned are approved. @gcasale

**Comment by gcasale** [comment]
Approved
