### ISSUE TITLE
R-T5.4-3: The data pipeline module of the Orchestrator should support event based scheduled data pipelines

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#17]
ID: | R-T5.4-3
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As an Operations Engineer, I want to be   able to trigger the data pipeline execution in Event-driven manner
Requirement: | The data pipeline module of the   Orchestrator should support event based scheduled data pipelines
Extended   Description: | Goal is to support data pipelines that   are executed on demand or in an event-driven manner.
Priority: | Should have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test data pipeline execution with   different event based triggers and verify that pipeline is executed every   single time

**Comment by anzoman** [comment]
Currently [xOpera](https://github.com/xlab-si/xopera-opera) does not include and explicit support for data pipelines. I am not sure if this has to be the part of the orchestrator but we certainly can create an issue on opera's GitHub repository and ask there.

**Comment by chinmaya-dehury** [comment]
For event based scheduling, the necessary properties are added to the parent node [radon.nodes.datapipeline.PipelineBlock](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline/PipelineBlock), which will be available to all the inherited child nodes. The respective configuration implementations are add to all the nodetypes.

This issue can be closed now. @gcasale

**Comment by gcasale** [comment]
OK

**Comment by chinmaya-dehury** [comment]
Please close this issue. @cankarm

**Comment by gcasale** [comment]
Approved
