### ISSUE TITLE
R-T5.4-4: It would be useful for the data pipeline module of the Orchestrator to support logging and generating alerts on   pipeline task failures.

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#18]
ID: | R-T5.4-4
-- | --
Type: | RELIABILITY
User   story: | As an QoS Engineer, I want to be notified   if the data pipeline execution fails
Requirement: | It would be useful for the data pipeline module of the Orchestrator to support logging and generating alerts on   pipeline task failures.
Extended   Description: | Goal is to support notifications for more   critical data pipelines, which would be raised when data pipeline tasks fail   or are overloaded.
Priority: | Should have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test data pipelines that have   notifications enabled, force critical situations to happen (e.g. by sending   malformed data, shutting down specific services or generating too much data)   and verify that alarms are raised

**Comment by anzoman** [comment]
Currently [xOpera](https://github.com/xlab-si/xopera-opera) does not include a special module for data pipelines and this enhancement has not been proposed there. Also look here: #17.

**Comment by chinmaya-dehury** [comment]
The data pipeline nodetypes, such as [AWSCopyDynamodbToS3](https://github.com/radon-h2020/radon-particles/blob/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSCopyDynamodbToS3/NodeType.tosca), [AWSEMRactivity](https://github.com/radon-h2020/radon-particles/blob/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSEMRactivity/NodeType.tosca), and others, are now having the features to support logging and generating alerts on pipeline task failures. Users are now able to provide the S3 bucket (through `log_bucket` and `log_directory` properties) to keep all the logs. The alerts on failure of tasks and pipelines can be generated and users will be notified through the AWS SNS service (using the `sns_arn_topic` properties).  

This issues can be closed now. @gcasale

**Comment by gcasale** [comment]
Approved
