### ISSUE TITLE
R-T5.4-5: The data pipeline module of the Orchestrator should support deployment of data pipelines which automate movement of data between two or more clouds

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#19]
ID: | R-T5.4-5
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy data pipelines across multiple (cloud) systems
Requirement: | The data pipeline module of the Orchestrator should support deployment of data pipelines which automate   movement of data between two or more clouds
Extended   Description: | Goal is to support data pipelines that   migrate data between different cloud providers and availability zones.
Priority: | Should have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test data pipeline orchestration where   different parts of the pipeline are deployed on different clouds

**Comment by anzoman** [comment]
Take a look at for my first comment here: #17.

**Comment by chinmaya-dehury** [comment]
A number of TOSCA node types are created to support the movement of data between two or more clouds. 

[`ConsGCSBucket`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.source/ConsS3Bucket), [`ConsAzureBlob`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.source/ConsAzureBlob), and [`ConsS3Bucket`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.source/ConsS3Bucket) are developed to consume data from 
Google Cloud Storage, Azure blob storage, and S3 bucket, respectively.

Similarly, [`PubGCS`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.destination/PubGCS), [`PubsAzureBlob`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.destination/PubsAzureBlob) and [`PubsS3Bucket`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.destination/PubsS3Bucket) are developed to publish data to Google Cloud Storage, Azure blob storage, and S3 bucket, respectively.

For private cloud, we have developed [`ConsumeLocal`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.source/ConsumeLocal) and [`PublishLocal`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.destination/PublishLocal).

This issue can be closed now. @gcasale

**Comment by gcasale** [comment]
Approved
