### ISSUE TITLE
R-T5.4-6: The data pipeline module must support   data pipelines tasks that initiate data analytics tasks for processing data moving through the pipeline

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#20]
ID: | R-T5.4-6
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As an Operations Engineer, I want to be   able to deploy data pipelines that trigger NLP data analytics jobs
Requirement: | The data pipeline module must support   data pipelines tasks that initiate data analytics tasks for processing data   moving through the pipeline
Extended   Description: | Goal is to support defining data   pipelines that initiate analytics jobs in large scale data processing   frameworks (e.g Hadoop, Spark, Flink) as one of the pipeline actions.
Priority: | Must have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test data pipelines that include   initiating data analytics jobs as one or more pipeline tasks  and verify that resulting data is correct.

**Comment by anzoman** [comment]
Take a look at for my first comment here: #17.

**Comment by chinmaya-dehury** [comment]
To fulfill this requirement, [AWSEMRActivity ](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSEMRactivity) is created that initiates the data analytics tasks atop EMR cluster in Amazon Cloud platform for processing data moving through the pipeline. 

This issue can be closed now. @gcasale

**Comment by gcasale** [comment]
Agreed

**Comment by chinmaya-dehury** [comment]
Please close this issue. @cankarm
