### ISSUE TITLE
R-T5.4-7: The data pipeline module of the Orchestrator should support configuring encryption between data pipeline tasks when data needs to be moved between systems

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#21]
ID: | R-T5.4-7
-- | --
Type: | SECURITY
User   story: | As an Operations Engineer, I want to be   able to configure encryption for data moving throgh the data pipeline
Requirement: | The data pipeline module of the   Orchestrator should support configuring encryption between data pipeline   tasks when data needs to be moved between systems
Extended   Description: | Goal is to support automatic data   encryption pipes when data is transported between/outside cloud enviorement.   Service mesh can be adapted for this.
Priority: | Should have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test data pipelines that move data   between two systems. Analyze network traffic and verify data is not sent   unencrypted.

**Comment by anzoman** [comment]
Take a look at for my first comment here: #17.

**Comment by chinmaya-dehury** [comment]
To provide the encryption feature, we have created TOSCA data pipeline node types for encryption ([Encrypt TOSCA node](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.process/Encrypt)) and decryption ([Decrypt TOSCA node](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.process/Decrypt)).  This issue can be closed now. @gcasale

**Comment by cankarm** [comment]
Hi, I would just like to clarify something. I see there is a `create.yml` and I don't see `delete.yml`. I hope that this is used in a way that `opera undeloy` will still clean everything? Or this is missing here?

Thanks for the clarification.

**Comment by chinmaya-dehury** [comment]
For `opera undeploy`, the definition of `delete ` operation and corresponding implementation (`delete.yml`) are in the [`parent TOSCA node`](https://github.com/radon-h2020/radon-particles/blob/master/nodetypes/radon.nodes.datapipeline/PipelineBlock/NodeType.tosca). the parent TOSCA node also provides the definition for `start` and `stop` operations.

**Comment by cankarm** [comment]
Ok, great, thanks!

**Comment by gcasale** [comment]
Approved
