### ISSUE TITLE
R-T5.4-8: The data pipeline module of the   Orchestrator should support deploying data pipelines expressed using TOSCA models into the AWS data pipeline service.

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#22]
ID: | R-T5.4-8
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to   deploy data pipelines to AWS data pipeline service
Requirement: | The data pipeline module of the   Orchestrator should support deploying data pipelines expressed using TOSCA   models into the AWS data pipeline service.
Extended   Description: | The goal is to support deploying data   pipelines into an existing data pipeline service provided by Public clouds.   AWS data pipeline service is a reference case.
Priority: | Must have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Tests to verify that deployment to AWS   data pipeline service is successful

**Comment by anzoman** [comment]
Take a look at for my first comment here: #17.

**Comment by chinmaya-dehury** [comment]
A number of TOSCA node types are developed that deploy the data pipeline into AWS data pipeline service. For instance, [`AWSCopyS3ToDynamodb`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSCopyS3ToDynamodb) TOSCA node type can be used to create and deploy data pipeline into AWS data pipeline service to move data form S3 bucket to dynamo db. Some other related TOSCA node types are [`AWSCopyDynamodbToS3`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSCopyDynamodbToS3), [`AWSCopyS3ToS3`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSCopyS3ToS3), [`AWSShellCommand`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSShellCommand), and [`AWSSqlActivity`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.Standalone/AWSSqlActivity).

This issue can be closed now. @gcasale

**Comment by gcasale** [comment]
Approved
