### ISSUE TITLE
R-T5.4-9: The data pipeline module of the   Orchestrator should support deploying data pipelines expressed using TOSCA models into a private OpenStack cloud.

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#23]
ID: | R-T5.4-9
-- | --
Type: | PORTABILITY
User   story: | As an Operations Engineer, I want to   deploy data pipelines to Private clouds
Requirement: | The data pipeline module of the   Orchestrator should support deploying data pipelines expressed using TOSCA   models into a private OpenStack cloud.
Extended   Description: | The goal is to support deploying data   pipelines in open source cloud platforms designed for setting up private   clouds. OpenStack is chosen as the reference case. Open Source data pipeline   platofrm (e.g. Apache NiFi) will be used as the runtime for the dat
Priority: | Must have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Tests to verify that deployment to   private cloud platform is successful

**Comment by anzoman** [comment]
Take a look at for my first comment here: #17.

**Comment by chinmaya-dehury** [comment]
As the available TOSCA node types and the related Ansible implementation are ready in radon-particles repo, this issue can be closed now. @gcasale .

**Comment by gcasale** [comment]
OK

**Comment by chinmaya-dehury** [comment]
Thanks @gcasale .
Can we please close this issue now, @cankarm ?

**Comment by cankarm** [comment]
Thanks for the contribution!
