### ISSUE TITLE
R-T5.5-1: The xOpera command line interface needs to have a dry run mode to verify changes without asking for input in execution

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#29]
ID: | R-T5.5-1
-- | --
Type: | USABILITY
User   story: | As an Operations Engineer I want my   deploy stage to go through a CI tool so that my release is traceable
Requirement: | The xOpera command line interface needs   to have a dry run mode to verify changes without asking for input in   execution
Extended   Description: | a) The --dry-run flag (or something   similar) can give the user information about which changes will be activated.   b) if the cli has input to verify. A workaround is to add a --auto-approve   flag.
Priority: | Could have
Affected   Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means   of Verification: | Setting up a CI server

**Comment by cankarm** [comment]
@anzoman  what is status on that?

**Comment by anzoman** [comment]
@cankarm xOpera now has a command which validates and verifies TOSCA service template and tells if all definitions were parsed successfully and to warn the user if there are any possible errors. You can run this command from CLI, for instance by `opera validate -i inputs.yml service-template.yml` and this will execute some sort of dry run which includes parsing the template without the real execution of the deployment. The command allows you to decide whether to pass the inputs file if you have it or continue just with the service template. Is that the dry run you wanted here or should there be any additional functionalities?

**Comment by cankarm** [comment]
great @anzoman. Anyway it seems that this is almost this.

However it seems, that this should create "diff" between old and new blueprint. I need to rethink if this is actually a good idea.

**Comment by cankarm** [comment]
The "dry run" is achieved through the ```validate``` command. The diff is not sometnihg that orchestrator should do, but rather the outside scaler. I'm closing this one.
