### ISSUE TITLE
**RADON GMT and Orchestrator integration**

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#3]
This story defines the requirements for the GMT (Winery) and orchestrator (xOpera) integration.

Requires:
radon-h2020/winery#1
radon-h2020/winery#2
radon-h2020/winery#3
radon-h2020/xopera-opera#1
xlab-si/xopera-opera#27

**Comment by anzoman** [comment]
The last link you posted here is related to this final requirement: #34.

**Comment by cankarm** [comment]
From what I see, all related requirements are achieved.
Closing the issue.
