### ISSUE TITLE
Allow to link aws layers (by arn) when deploying aws lambda functions

### ISSUE THREAD

**Issue by giopnd** [radon-h2020/radon-delivery-toolchain#30]
extend TOSCA blueprints to support reference a set of layers (by arn version) and specify a merge order. 

when the dependencies package exceeds 50Mb of size you are not allowed to upload the dependencies package along with the lambda code (only through S3) and it is the case to use layers. 
we need this for the ATC's named entities extractor lambda function.

**Comment by cankarm** [comment]
Is this resolved now? @giopnd ?

**Comment by giopnd** [comment]
Yes it is resolved. the node type [AwsLambdaFunctionFromS3](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.aws/AwsLambdaFunctionFromS3) provides the required functionality in an elegant way making it possible to deploy aws Lambda functions having a deployment package that exceeds 50Mb by uploading it to an S3 bucket and deploy it from there.
