### ISSUE TITLE
FR-T5.1-8: xOpera orchestrator should provide the support for compressed CSARs

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#34]
ID: | FR-T5.1-8
-- | --
Type: | USABILITY
User  story: | As a user I would want to directly deploy the prepacked compressed CSAR file that includes all TOSCA templates accompanied by all other necessary artifacts (like prepared FaaS functions, Ansible playbooks, config files and so on)
Requirement: | The xOpera command line interface now supports deploying only the uncompressed CSARs. So it would be helpful that could recognize zip compressed TOSCA template files and will allow to either deploy or undeploy the service template from CSAR.
Extended Description: | To incorporate the support for compressed CSAR files the deployment process of zipped CSAR fille could feature the following steps:  <ul><li>use `opera init -i inputs.yml archive.csar` to initialize CSAR</li><li>use `opera deploy` to deploy the stored CSAR</li><li>use `opera undeploy` to undeploy the compressed CSAR</li></ul>
Priority: | Must have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Test to deploy a zipped CSAR file or the prepared CSAR files from Winery or RADON particles

**Comment by cankarm** [comment]
I approve this one.

@gcasale , please confirm.

**Comment by gcasale** [comment]
Accepted

**Comment by cankarm** [comment]
Will be available in the next orchestrato release.

Functionality has been added with the following PR: https://github.com/xlab-si/xopera-opera/pull/55

**Comment by anzoman** [comment]
The support for compressed CSARs was added in opera version [0.5.8](https://github.com/xlab-si/xopera-opera/releases/tag/0.5.8).

**Comment by gcasale** [comment]
OK to close
