### ISSUE TITLE
FR-T5.1-9: xOpera orchestrator should be available as a service/RADON SaaS component

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#35]
ID: | FR-T5.1-9
-- | --
Type: | USABILITY
User  story: | As a user I want to deploy my prepared TOSCA templates/CSARs using the SaaS orchestrator and I would only need to supply the prepared files and then the orchestration would begin.
Requirement: | For users it would be useful to have multiple interaction modes. One of them is already supported and is a CLI that is meant to be used in shell sessions. Another one would be the SaaS component that would offer an API which would provide the endpoints for the orchestration and managing other stuff (users, secrets and so on).
Extended Description: | One possible way to implement the SaaS component would feature two APIs - one that would serve as xOpera API and would offer the endpoint calls which would correspond to the CLI commands (like validate, deploy, undeploy, outputs) and the second one which would be on top of the first one and would provide everything else (user and secrets management, projects, storing templates etc.). Another thing that would be welcome is the Web user interface which would simplify the interaction with the SaaS component.
Priority: | Must have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Successfully deploy prepared CSAR with the SaaS orchestartor component

**Comment by cankarm** [comment]
This is one is also ongoing task. 

@gcasale , please approve

**Comment by gcasale** [comment]
Approved

**Comment by anzoman** [comment]
This can be closed. We have already developed the SaaS orchestrator component that is currently available here: https://xopera-radon.xlab.si/ui and we are already preparing detailed documentation here: https://github.com/xlab-si/xopera-opera/pull/110.
