### ISSUE TITLE
FR-T5.3-5: SaaS orchestrator should be IAM compliant and should include proper level of security

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#36]
ID: | FR-T5.3-5
-- | --
Type: | USABILITY
User  story: | As a user I would want to use the SaaS orchestartor component independently from other users. To me it would be important to be able to manage my user account settings and to be sure that my secrets are safe and that the orchestration process that use those secrets can do no harm or expose them to some public place.
Requirement: | It seems necessary that the SaaS orchestrator would have user and access management included. The other important part that needs to be considered is the security because during the orchestration user could use his sensitive data like:  <ul><li>private SSH keys</li><li>cloud credentials (for AWS, Azure, GCP,...)</li><li>actual IPs</li><li>other passwords and secrets</li></ul> 
Extended Description: | Apart from user management the secrets for the orchestration could reside in `inputs.yaml` file that provides inputs for the orchestration. This file should not be stored by SaaS and should be used only during the process. Another good option is to use the environment variables for the secrets and expose them only when needed (at the end of the deployment they could be unset).
Priority: | Should have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Test user management and the deployment process using secrets.

**Comment by cankarm** [comment]
This is already an ongoing task.

@gcasale , please confirm.

**Comment by gcasale** [comment]
Approved

**Comment by anzoman** [comment]
@cankarm AFAIK this is is already implemented. @sstanovnik can you approve that we have this?

**Comment by cankarm** [comment]
This can be closed as the goal described by the title is achieved.

There is a slight difference from the extended description. The xOpera SaaS is developed in a way that each deploy is an isolated project inside a container. Therefore it is safe to store and manage credentials there, as they are not accessible to other projects. Consequently, there is no need to pass the credentials through the inputs. Still this can be done if desired.
