### ISSUE TITLE
FR-T5.1-10: TOSCA orchestrator could provide a packaging command to prepare CSAR files

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#39]
ID: | FR-T5.1-10
-- | --
Type: | USABILITY
User  story: | As a user I would want to easily prepare TOSCA CSAR file for the orchestration and compress it with all the accompanying files needed for the deployment
Requirement: | xOpera tool could provide a simple packaging command that would prepare the zipped version of the CSAR archieve which could then be used for the deployment or to transfer it somewhere.
Extended Description: | This could be resolved by establishing the `opera package` command which would create a CSAR file from the service template and all the accompanying files in the root directory.
Priority: | Could have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Package orchestration files to CSAR and deploy it with xOpera

**Comment by cankarm** [comment]
Good enhancement, but not crucial.

@gcasale, please review

**Comment by gcasale** [comment]
Unlikely to be needed in RADON but ok to keep as an idea.

**Comment by gcasale** [comment]
Accepted

**Comment by anzoman** [comment]
This is currently in future plans: https://github.com/xlab-si/xopera-opera/pull/42.

**Comment by anzoman** [comment]
The `opera package` and `opera unpackage` CLI commands used for preparing an unpacking TOSCA CSARs were introduced in opera version [0.6.3](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.3) and are also available in the latest opera version [0.6.4](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.4). I thus propose closing this issue.

cc @cankarm

**Comment by gcasale** [comment]
I agree and thanks for these great additions.

**Comment by cankarm** [comment]
Sure, @anzoman, I'm closing this issue.
