### ISSUE TITLE
FR-T5.1-11: xOpera should be able to parse get_artifact TOSCA function

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#40]
ID: | FR-T5.1-11
-- | --
Type: | USABILITY
User  story: | As a user I would want to use the prepared orchestration artifacts (e.g zipped FaaS function files) directly in a sevice template.
Requirement: | xOpera tool should have a support for `get_artifact` TOSCA function that is used to retrieve artifact location between entities defined in the same service template.
Extended Description: | Here the support for full TOSCA artifact function should be added and then the function could be used like this:  `get_artifact: [ <modelable_entity_name>, <artifact_name>, <location>, <remove> ]`.
Priority: | Should have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Try to deploy a service template that uses `get_artifact` TOSCA function.

**Comment by cankarm** [comment]
Thanks @anzoman, 
@gcasale  to review

**Comment by gcasale** [comment]
This seems a must?

**Comment by cankarm** [comment]
This gives a better user experience and makes templates even more general, as it is possible to change/inject new artefacts (FaaS functions) in existing templates.
 
However, I don't see it as a must.

**Comment by gcasale** [comment]
Accepted

**Comment by anzoman** [comment]
Opera [0.6.0](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.0) now supports using `get_artifact` TOSCA function.

**Comment by gcasale** [comment]
OK to close
