### ISSUE TITLE
FR-T5.1-12: Orchestrator should consider each deployment separately

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#41]
ID: | FR-T5.1-12
-- | --
Type: | USABILITY
User  story: | xOpera users would usually want to distinguish each deployment and when they run they would want to be treated separately from all other deployments that have been/would be created before/after. 
Requirement: | xOpera TOSCA orchestration tool should implement a different behaviour of treating the deployment runned by `opera deploy`. This means that user would tell if he needs to resume the actual deployment or start over the completely new one.
Extended Description: | The requirement could be implemented with the following command options: <ul><li>if user runs `opera deploy` on the already deployed instance he gets an error saying that the deploy has already been done or partially done</li><li> run `opera deploy --resume` which would diplay a warning, but the deploy would resume</li><li>use `opera deploy --force` which would delete the previous instance model and create a new, fresh one</li></ul>
Priority: | Should have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Try to deploy a service template with all the aforementioned options.

**Comment by cankarm** [comment]
This requirement is relevant and the basics have been discussed also here: https://github.com/xlab-si/xopera-opera/issues/46.

@gcasale: please review.

**Comment by gcasale** [comment]
Accepted

**Comment by anzoman** [comment]
This was realized with this PR: https://github.com/xlab-si/xopera-opera/issues/46 and is available in the latest opera version [0.6.0](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.0).

**Comment by gcasale** [comment]
OK to close

**Comment by anzoman** [comment]
With the new opera deploy command switches we have increased orchestrator's usability and assured that the orchestrator will treat deployments separately when needed. Therefore we can close this.
