### ISSUE TITLE
FR-T5.2-14: Generating a basic entity with template library CLI

### ISSUE THREAD

**Issue by neza-vehovar** [radon-h2020/radon-delivery-toolchain#43]
ID: | FR-T5.2-14
-- | --
Type: | USABILITY
User   story: | As a user I would like to be able to generate a basic entity.
Requirement: | User should be able to generate an entity directory structure.
Extended   Description: | Template library CLI command for generating an entity directory structure with all necessary files, so that creating a template is made easier for the user and common issues regarding the entity structure are avoided.
Priority: | Could have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Use template library CLI command to generate an entity.

**Comment by cankarm** [comment]
This is an enchancement based on user requirements. 

@gcasale , please confirm a new requirement and remove "workinprogress" label.

**Comment by gcasale** [comment]
Approved.

**Comment by anzoman** [comment]
[Template library CLI](https://pypi.org/project/xopera-template-library/) is now capable of generating a basic model with the structure similar to the one used in Winery/radon-particles. This model helps users to create consistent TPS models, which can then be modified and stored to Template library service.

A simple example:

```console
(.venv) anzoman@ubuntu:~/Desktop/template-library-cli$ xopera-template-library template create -h
usage: xopera-template-library template create [-h] [--name NAME]
                                               [--type TYPE]

optional arguments:
  -h, --help   show this help message and exit
  --name NAME  Name of the template.
  --type TYPE  Template type name.

(.venv) anzoman@ubuntu:~/Desktop/template-library-cli$ xopera-template-library template create
Template type: node
Template name: test
Model 'test' created.

(.venv) anzoman@ubuntu:~/Desktop/template-library-cli$ tree test
test
├── files
│   ├── create.yml
│   └── delete.yml
├── NodeType.tosca
└── README.md

1 directory, 4 files

# modify the created model and then use the command below to upload the model to TPS 
(.venv) anzoman@ubuntu:~/Desktop/template-library-cli$ xopera-template-library template save -h
usage: xopera-template-library template save [-h] [--name NAME]
                                             [--description DESCRIPTION]
                                             [--path PATH] [--version VERSION]
                                             [--public]

optional arguments:
  -h, --help            show this help message and exit
  --name NAME           Name of the template.
  --description DESCRIPTION
                        Description of the template.
  --path PATH           Path to the template directory.
  --version VERSION     Version name of the template to upload (e.g. 1.3.0)
  --public              Template is available to the public

```

cc @cankarm

**Comment by cankarm** [comment]
Hey, that seems nice.

Is there any convention about the versioning of those templates? In other words, it is possible that CASR structures would change at some point in time?

I know that this is a "long shot" but I would like to understand now if this is already possible. Do you know anything about that?

**Comment by anzoman** [comment]
These files that are generated with the TPS CLI can change if the Winery/radon-particles changes the structure. With this `create` TPS CLI subcommand we just want to make TPS models compatible with Winery, but the user can still upload his own structure if he wants or change this structure with a new template version.

Another thing is that the generated structure above is not a proper TOSCA CSAR (for that it should also have `TOSCA.meta` file or `metadata` entry in its service template). If we are talking from this perspective I don't think that TOSCA CSARs will change much.

**Comment by cankarm** [comment]
Thanks, that's perfect!

We can close this, please confirm @gcasale.

**Comment by cankarm** [comment]
I'm closing this, due to the inactivity. @gcasale

**Comment by gcasale** [comment]
Approved
