### ISSUE TITLE
FR-T5.1-13: Orchestrator could support using ssh private keys

### ISSUE THREAD

**Issue by anzoman** [radon-h2020/radon-delivery-toolchain#44]
ID: | FR-T5.1-13
-- | --
Type: | USABILITY
User  story: | As a user of the xOpera tool  I would want to point the orchestrator to my private key that needs to be used for the connection to the remote machine.
Requirement: | As of now xOpera orchestrator offers  `OPERA_SSH_USER` environment variable which is used by the Ansible executor when establishing the connection to a remote machine to tell which user someone wants to connect as. Currently xOpera does not offer to choose ssh keys to connect but it expects that user managed that before by himself either with putting keys to the ~/.ssh folder or by creating ~/.ssh/config configuration file which offers matching IPs and ssh keys for connection. Similar to that there could be a variable called `OPERA_SSH_IDENTITY_FILE` that would point to the file with a private ssh key that needs to be used when establishing a connection to the host.
Extended Description: | To implement the part for the ssh keys the following would need to be done: <ul><li>use `OPERA_SSH_IDENTITIY_FILE` env var to point opera to the ssh key</li><li>check the path to the ssh key file</li><li>set the shh key in the opera's Ansible inventory with ansible_ssh_private_key_file entry</li></ul>
Priority: | Could have
Affected Tools: | DELIVERY_TOOLCHAIN, ORCHESTRATOR
Means of Verification: | Try to deploy an application blueprint (e.g. OpenFaaS setup) on the remote VM by using the `OPERA_SSH_IDENTITY_FILE` env var.

**Comment by cankarm** [comment]
This request is not crucial for RADON as the targeted users (FaaS developers) do not desperately need SSH. However in microservice scenario this could be beneficial to have. 
Therefore "Could have"
@gcasale

**Comment by gcasale** [comment]
Accepted

**Comment by anzoman** [comment]
This feature has been implemented within this PR: https://github.com/xlab-si/xopera-opera/pull/61 and `OPERA_SSH_IDENTITY_FILE` env var will be available for use with the new opera version.

**Comment by gcasale** [comment]
OK to close.

**Comment by anzoman** [comment]
The feature is already available in [`0.6.0`](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.0) opera's release.

**Comment by anzoman** [comment]
I'm closing this issue since we have completed its objective by supporting private keys within opera.
