### ISSUE TITLE
FR-T5.2-15: Publishing and retrieving entities with template library CLI

### ISSUE THREAD

**Issue by neza-vehovar** [radon-h2020/radon-delivery-toolchain#45]
ID: | FR-T5.2-15
-- | --
Type: | USABILITY
User   story: | As a user I want to be able to save entities by versions and retrieve them when needed.
Requirement: | Template library publishing service needs to enable saving entities and adding new versions. User needs to be able to retrieve a version.
Extended   Description: |  Versions need to be unchangeable entries that offer stability in the development stage of RADON applications.
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Use template library CLI to save a version of an entity and retrieve it.

**Comment by gcasale** [comment]
Accepted

**Comment by cankarm** [comment]
This one is achieved through the EclipseChe and CLI. For more details follow https://template-library-radon.xlab.si/docs/.
