### ISSUE TITLE
FR-T5.2-16: Listing versions of a template with template library CLI

### ISSUE THREAD

**Issue by neza-vehovar** [radon-h2020/radon-delivery-toolchain#46]
ID: | FR-T5.2-16
-- | --
Type: | USABILITY
User   story: | As a user I would like to list all the versions of a template.
Requirement: | Template library CLI must support listing versions.
Extended   Description: | Listing versions should be done by the name of a template or by the ID of the template.
Priority: | Must have
Affected   Tools: | TEMPLATE_LIBRARY
Means   of Verification: | Using template library CLI command to list all versions of a template (by name or id of the template).

**Comment by cankarm** [comment]
The priority is "must" because, without the ability to list/access versions, user cannot download a particular version.
@gcasale to confirm.

**Comment by gcasale** [comment]
Accepted

**Comment by cankarm** [comment]
![2020-11-11 15_21_03-Screenshots](https://user-images.githubusercontent.com/2518386/100233237-bf06f180-2f29-11eb-88da-2abd8f16537a.png)

This is done in CLI version.
