### ISSUE TITLE
R-T5.1-1: The orchestrator tasks must be executable through CLI

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#5]
ID: | R-T5.1-1
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As an Operations Engineer, I want to use   orchestrator through command line
Requirement: | The orchestrator tasks must be executable   through CLI
Extended   Description: | Orchestrator should provide CLI to manage   the deployment of blueprints on serverless and FaaS providers
Priority: | Should have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Test if deployment of RADON model is   possible using only CLI.

**Comment by anzoman** [comment]
[xOpera](https://github.com/xlab-si/xopera-opera) orchestrator is currently available as a CLI tool. We also have prepared, provided and tested several TOSCA CSAR files(blueprints) and templates that reside in these repositories:

- https://github.com/radon-h2020/demo-tosca-blueprint-aws-lambda
- https://github.com/radon-h2020/demo-tosca-blueprint-azure-function
- https://github.com/radon-h2020/demo-tosca-blueprint-openfaas

xOpera repository also provides [nightly integration tests](https://github.com/xlab-si/xopera-opera/tree/master/tests/integration/) with the prepared CSARs that make sure that opera deployment keeps working. And with every new release a bunch of unit tests are executed to make sure that the parser works correctly.

So @cankarm can we close this or is there anything else that needs to be validated?

**Comment by anzoman** [comment]
Tasks are executable through CLI and this was tested numerous times now. So, I think that the time is right to close this.
