### ISSUE TITLE
R-T5.4-2 The data pipeline module of the Orchestrator must support cron based scheduled data pipelines.

### ISSUE THREAD

**Issue by chinmaya-dehury** [radon-h2020/radon-delivery-toolchain#50]
ID | R-T5.4-2
-- | --
Section | WP5: Runtime environment
Type | FUNCTIONAL_SUITABILITY
User Story | As an Operations Engineer, I want to be able to schedule data pipelines periodically.
Requirement | The data pipeline module of the Orchestrator must support cron based scheduled data pipelines.
Extended Description | Goal is to allow users to configure specific times and intervals when the data pipeline is executed. 
Priority | Must have
Affected Tools | ORCHESTRATOR
Means of Verification | Test data pipeline execution with different time based periodic schedules and verify that pipeline is executed every single time.

**Comment by chinmaya-dehury** [comment]
Missing requirement added. Please verify for approval @gcasale .

**Comment by gcasale** [comment]
Approved

**Comment by chinmaya-dehury** [comment]
Please add "Data Pipelines" label to this issue  @cankarm .

**Comment by cankarm** [comment]
@chinmaya-dehury done. I was not aware that you are not able to do it yourself.

**Comment by chinmaya-dehury** [comment]
For CRON based scheduling, the necessary properties are added to the parent node [radon.nodes.datapipeline.PipelineBlock](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline/PipelineBlock), which will be available to all the inherited child nodes. The respective configuration implementations are added to all the node types.

This issue can be closed now. @gcasale

**Comment by gcasale** [comment]
Agreed

**Comment by chinmaya-dehury** [comment]
Thank you. This is closed now.
