### ISSUE TITLE
R-T5.1-2: A Software Developer describes the application architecture and dependencies at least in TOSCA YAML 1.2

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#6]
ID: | R-T5.1-2
-- | --
Type: | FUNCTIONAL_SUITABILITY
User   story: | As a Software Developer, I want to   describe application in TOSCA YAML 1.2
Requirement: | A Software Developer describes the   application architecture and dependencies at least in TOSCA YAML 1.2
Extended   Description: | The TOSCA blueprints, input to   orchestrator, must be written in TOSCA YAML 1.2 syntax, at minimum.
Priority: | Must have
Affected   Tools: | DELIVERY_TOOLCHAIN
Means   of Verification: | The orchestrator should report error in   case the blueprint is not in TOSCA YAML 1.2

**Comment by cankarm** [comment]
Updated - during the project we decided to go wiht TOSCA 1.3 version.

**Comment by anzoman** [comment]
As of now [xOpera](https://github.com/xlab-si/xopera-opera) provides compliance with the [TOSCA Simple Profile in YAML v1.3.](https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/cos01/TOSCA-Simple-Profile-YAML-v1.3-cos01.html). That can also be evident from:

- TOSCA template examples in https://github.com/xlab-si/xopera-opera/tree/master/examples
- opera's integration tests in: https://github.com/xlab-si/xopera-opera/tree/master/tests/integration/
- opera's TOSCA parser in https://github.com/xlab-si/xopera-opera/tree/master/src/opera/parser/tosca

Therefore I propose closing this issue.

**Comment by anzoman** [comment]
This is done and can be closed.
