### ISSUE TITLE
R-T5.1-3: The runtime toolchain need to provide a status on each stage of deployment of the application on the underlying   architecture

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#7]
ID: | R-T5.1-3
-- | --
Type: | USABILITY
User   story: | As an Operations Engineer, I want to see   the status of runtime deployment of application in each stage
Requirement: | The runtime toolchain need to provide a   status on each stage of deployment of the application on the underlying   architecture
Extended   Description: | Using different technologies for   monitoring the deployment process, a service or tool must be developed to keep   users updated on the status of the deployment process. In case of errors they   should be immediatly reported.
Priority: | Must have
Affected   Tools: | MONITORING_SYSTEM
Means   of Verification: | During runtime execution the log of   activites/steps must be available.

**Comment by anzoman** [comment]
xOpera currently provides status of the deployment in the storage folder that is created in `.opera` folder. Here the subfolder `instances` gets created when the deployment starts and for each instance the status can be seen. The statuses (states) are named like: `initial`, `created`, `started` and so on.

This is also evident here: https://github.com/xlab-si/xopera-opera/blob/ffe72a4dce9ac24f33304582577fed7b56ae34cd/src/opera/instance/node.py#L30.

**Comment by anzoman** [comment]
There has been an update for the opera orchestrator. Now we have [`opera info` ](https://github.com/xlab-si/xopera-opera/pull/106) CLI command that is meant to inform user about the current opera project and would allow him to access its storage and state. User can execute it anytime and he will get a JSON/YAML output that looks like this:

```
{
   "service_template":  "string | null",
   "content_root":      "string | null",
   "inputs":            "string | null",
   "status":            "initialized | deployed | undeployed | interrupted | null"
}
```

So basically user can find out what has happened or is happening with his initalization/deployment or undeployment process by receiving the status and the files that are being used for the operation. I think that this is exactly what we target here - to get a status on each stage of deployment of the application.

**Comment by cankarm** [comment]
Statuses are quite evident from the xOpera SaaS version, together with the detailed progress output. 

The only question here is if we need to connect this with the monitoring system or it is not needed (as this is a deployment process, not monitoring of an application). @giopnd, what do you think?

**Comment by giopnd** [comment]
I think that the monitoring system does not fit in this context since it refers to the monitoring of the runtime behavior of an application. There are no metrics to monitor during the deployment stages. 
Btw the 'opera info' functionality looks nice.

**Comment by anzoman** [comment]
@cankarm since `opera info` is available and can be used at any stage of orchestration to show the information about the current project status, do you think that this is done and can be closed? I also see that the status can be monitored with radon-monitoring-tool.

**Comment by cankarm** [comment]
Additionally, if something is deployed using xOperaSaaS, user can get the status from the xOperaSaaS GUI or through a response on the API call.

We can close this if @giopnd agrees.

**Comment by cankarm** [comment]
@gcasale, can we close this?
 
 using `opera info` and xOperaSaaS GUI (or API) user can get the details of the current deployment status.

**Comment by gcasale** [comment]
Approved
