### ISSUE TITLE
R-T5.1-5: The orchestrator should be able to calculate the diff between the current state and the desired state expressed by a new model version and redeploy only the difference.

### ISSUE THREAD

**Issue by cankarm** [radon-h2020/radon-delivery-toolchain#9]
ID: | R-T5.1-5
-- | --
Type: | PERFORMANCE_EFFICIENCY
User   story: | As an Operations Engineer, I want to   update my deployment based on a small change in the model.
Requirement: | The orchestrator should be able to   calculate the diff between the current state and the desired state expressed   by a new model version and redeploy only the difference.
Extended   Description: | The orchestrator only need to execute   delta updates instead of redeploying all services, making redeployment more   efficient and in shorter time than with conventional way of deleting   everything and deploy it again.
Priority: | Must have
Affected   Tools: | ORCHESTRATOR
Means   of Verification: | Manually check if only the changed part   of blueprint was deployed

**Comment by sstanovnik** [comment]
Referencing the extended description in the OP, there are two features that can be enabled without much breaking changes:

1. updating the application version by specifying the version in the xopera-opera `inputs.yml`. This would redeploy only the application, because the execution backend (Ansible) already only performs necessary changes, and doesn't delete anything.
2. updating a TOSCA module version - e.g. updating the version of the module that handles AWS S3 buckets. Having a backwards compatible API, the module gets updated, but nothing gets changed, because there are no semantic changes.

This may already be enough to satisfy the requirement, as other deployment diffs are _very_ nontrivial, because the application and the blueprint need to be written in a way that is _synergises_ with the way it will be updated.

**Comment by anzoman** [comment]
This can be somehow related to this issue: #41 where it is stated that xOpera shuold consider the deployments separately and would have special CLI options to resume or start over the deployment.

**Comment by anzoman** [comment]
Connected also to #29.

**Comment by cankarm** [comment]
I would like to close this issue without a resolution because a diff of two yaml's cannot be utilised in a way that it was expected at start. Deploying one blueprint and then "redeploying" another one over the first one can work only in limited way. Those useful diffs are mostly addressed by the diff of ```inputs.yaml``` - so changes in configuration. More complex application changes cannot be achieved so easy due to the lack of TOSCA support. For example, there is a possibility to add more nodes to the application (install them, connect them), but there is no proper way to remove them. There is no "targeted undeploy" for just a few nodes. 

Some of this issues were discussed also in the discussion of TOSCA scaling.

The diff can also be seen graphically form the GMT if desired with versioning option.

@gcasale : I would like to get an approval for change/close of this issue.

**Comment by cankarm** [comment]
Additional information that I forget to mention before - RADON GMT has an option that crates diff between different versions of bluepritnts. Therefore the priority change. 

I propose to lover the priority from "must" to "could", as this functionality is provided by RADON GMT (diff between versions) and therefore is not so necessary to develop this part.

**Comment by cankarm** [comment]
At the time of the project, the focus of the users is on the day-one operations, therefore there is no urgent request that this functionality should be added into the project.

@gcasale  I propose that we change this to SHOULD. 

We can re-evaluate after when/if this functionality will gain more interest.

**Comment by gcasale** [comment]
Agreed, this is not a primary usage scenario - I approve this change.

**Comment by cankarm** [comment]
Related with https://github.com/xlab-si/xopera-opera/issues/130.

**Comment by anzoman** [comment]
Good news - with the [latest](https://pypi.org/project/opera/0.6.4/) opera version ([0.6.4](https://github.com/xlab-si/xopera-opera/releases/tag/0.6.4)) we introduced `opera diff` CLI command that finds and displays the differences between the deployed blueprint and supplied blueprint. User can also invoke `opera update` command that would calculate diff and redeploy the blueprint according to the discovered changes. So, I believe that this issue can be closed.

cc @cankarm

**Comment by gcasale** [comment]
Agreed
